name: Publish Python package to TestPyPI using OIDC

on:
  push:
    # Publish when a new release tag like `v0.1.0` is pushed
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to checkout the code

jobs:
  build-and-publish:
    environment: testpypi  # Matches the environment you will create in repo settings
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build wheel and sdist
        run: python -m build --sdist --wheel --outdir dist

      - name: Publish distribution to TestPyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true